import = ["/Users/andrewbeach/.config/alacritty/current-theme.toml"]

[font]
size = 13

[font.bold]
family = "Fira Code"
style = "SemiBold"

[font.normal]
family = "Fira Code"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "ClearHistory"
key = "K"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[105;5u"
key = "I"
mods = "Control"

[scrolling]
multiplier = 40

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "buttonless"
opacity = 0.8

[window.padding]
x = 16
y = 16
